config/routes.rb
Rails.application.routes.draw do
  get 'user/all'  => 'user#all'
  devise_for :users, path_names: { sign_in: "login", sign_out: "logout"}
  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "todos#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, presence: true, uniqueness: true
end

app/controllers/Model/confirmations_controller.rb
# frozen_string_literal: true

class Model::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/Model/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Model::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/Model/passwords_controller.rb
# frozen_string_literal: true

class Model::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/Model/registrations_controller.rb
# frozen_string_literal: true

class Model::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/Model/sessions_controller.rb
# frozen_string_literal: true

class Model::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/Model/unlocks_controller.rb
# frozen_string_literal: true

class Model::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    def after_sign_in_path_for(resource)
        "/todos"
    end

    def after_sign_out_path_for(resource)
        "/users/login"
    end

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
      end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!, only: :show
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(name:params[:todo],user_name:current_user.username)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo作ったよ！' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo更新したよ！' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo消しちゃった！' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, only: :all

  def all
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="ui borderless main menu">
    <div class="ui text container">
      <div class="header item">
        <img class="logo" src="/gopher.gif">
        Todoリスト
        <img class="logo" src="/gopher.gif">
      </div>
      <% if user_session %>
      <a rel="nofollow" class="item" data-method="delete" href="/users/logout">ログアウト</a>
      <a rel="nofollow" href="/todos/new" class="item">Todo作成</a>
      <a rel="nofollow" href="/todos" class="item">Todo一覧</a>
      <a rel="nofollow" href="/user/all" class="item">ユーザ一覧</a>
      <% else %>
      <a rel="nofollow" class="item" href="/users/login">ログイン</a>
      <% end %>
    </div>
  </div>
  <div class="ui main contener">
    <% if notice %>
    <p class="mes"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="mes"><%= alert %></p>
    <% end %>
      <%= yield %>
  </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label for="todo_name">やること</label>
    <p><input type="text" name="todo" id="todo_name"/></p>
  </div>

  <div class="actions">
    <input type="submit" name="commit" value="Todo作成！" data-disable-with="Create Todo"/>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Todo編集するマン</h1>

<%= render 'form', todo: @todo %>

<p><%= link_to '詳細', @todo %> |
<%= link_to '戻る', todos_path %></p>

app/views/todos/index.html.erb
<h1>Todo一覧だお</h1>

<% if @todos %>
<table class="ui celled table">
  <thead>
    <tr>
      <th><h2>やること</h2></th>
      <th><h2>ユーザ名</h2></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
    <% if todo.user_name == current_user.username %>
    <div class="item">
      <tr>
        <td data-label="やること"><%= todo.name %></td>
        <td data-label="ユーザ名"><%= todo.user_name %></td>
        <td><%= link_to '詳細', todo %></td>
        <td><%= link_to '編集', edit_todo_path(todo) %></td>
        <td><%= link_to '削除', todo, method: :delete, data: { confirm: '本当に消していいの???' } %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<% end %>
<%# <table class="ui celled table">
  <thead>
    <tr>
    <th>ToDo</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td data-label="Name"></td>
    </tr>
  </tbody>
</table> %>
<br>

<h1><%= link_to 'Todo作成', new_todo_path %></h1>
<h1><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></h1>

app/views/todos/new.html.erb
<h1>新規Todo</h1>

<%= render 'form', todo: @todo %>

<p><%= link_to 'Back', todos_path %></p>

app/views/todos/show.html.erb
<p>
  <h1>ToDo:
  <%= @todo.name %>
  </h1>
</p>

<p><%= link_to '編集', edit_todo_path(@todo) %> |
<%= link_to '戻る', todos_path %></p>

app/views/user/all.html.erb
<h1>ユーザ一覧だお</h1>

<% if @users %>
<table class="ui celled table">
  <thead>
    <tr>
      <th><h2>ユーザ名</h2></th>
      <th><h2>ログイン回数</h2></th>
      <th><h2>最終ログイン</h2></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <div class="item">
      <tr>
        <td data-label="ユーザ名"><%= user.username %></td>
        <td data-label="ログイン回数"><%= user.sign_in_count %></td>
        <td data-label="最終ログイン"><%= user.last_sign_in_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>